options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Check for changes in the summary function
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --quiet HEAD~1 HEAD -- cloudfunctions/summary || git diff --quiet HEAD~1 HEAD -- utils; then
          echo "No changes in 'summary' or 'utils', skipping deployment."
          exit 0
        fi
        echo "Changes detected in 'summary' or 'utils'. Proceeding with deployment."

  # Deploy summary cloud function if there are changes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd cloudfunctions/summary
        cp -r ../../utils .  # Copy utils to the function folder
        gcloud functions deploy summary \
          --runtime python310 \
          --entry-point hello_world \
          --trigger-http \
          --region us-central1 \
          --source .

  # Check for changes in the sentiment function
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --quiet HEAD~1 HEAD -- cloudfunctions/sentimet || git diff --quiet HEAD~1 HEAD -- utils; then
          echo "No changes in 'sentiment' or 'utils', skipping deployment."
          exit 0
        fi
        echo "Changes detected in 'sentiment' or 'utils'. Proceeding with deployment."

  # Deploy sentiment cloud function if there are changes
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd cloudfunctions/sentimet
        cp -r ../../utils .  # Copy utils to the function folder
        gcloud functions deploy sentiment \
          --runtime python310 \
          --entry-point hello_world \
          --trigger-http \
          --region us-central1 \
          --source .

timeout: 1200s
