options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Fetch the full history to avoid shallow clone issues
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'git fetch --unshallow']

  # Check for changes in the summary function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: check-summary
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking for changes in 'summary' folder..."
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          if git diff --quiet HEAD~1 HEAD -- cloudfunctions/summary; then
            echo "No changes in 'summary', skipping deployment."
            exit 0  # No changes, exit successfully
          else
            echo "Changes detected in 'summary'. Proceeding with deployment."
            exit 1  # Indicate that there are changes
          fi
        else
          echo "First commit or no previous commit, proceeding with deployment."
          exit 1  # Indicate that there are changes
        fi

  # Deploy summary cloud function if there are changes (run only when check-summary exits with status 1)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy-summary
    entrypoint: 'bash'
    waitFor: ['check-summary']
    if: '$(steps.check-summary.exit_code) == 1'  # Deploy only if changes detected
    args:
      - '-c'
      - |
        cd cloudfunctions/summary
        cp -r ../../utils .  # Copy utils to the function folder
        gcloud functions deploy summary \
          --runtime python310 \
          --entry-point hello_world \
          --trigger-http \
          --region us-central1 \
          --source .

  # Check for changes in the sentimet function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: check-sentimet
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking for changes in 'sentimet' folder..."
        if git rev-parse HEAD~1 >/dev/null 2>&1; then
          if git diff --quiet HEAD~1 HEAD -- cloudfunctions/sentimet; then
            echo "No changes in 'sentimet', skipping deployment."
            exit 0  # No changes, exit successfully
          else
            echo "Changes detected in 'sentimet'. Proceeding with deployment."
            exit 1  # Indicate that there are changes
          fi
        else
          echo "First commit or no previous commit, proceeding with deployment."
          exit 1  # Indicate that there are changes
        fi

  # Deploy sentimet cloud function if there are changes (run only when check-sentimet exits with status 1)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy-sentimet
    entrypoint: 'bash'
    waitFor: ['check-sentimet']
    if: '$(steps.check-sentimet.exit_code) == 1'  # Deploy only if changes detected
    args:
      - '-c'
      - |
        cd cloudfunctions/sentimet
        cp -r ../../utils .  # Copy utils to the function folder
        gcloud functions deploy sentimet \
          --runtime python310 \
          --entry-point hello_world \
          --trigger-http \
          --region us-central1 \
          --source .

timeout: 1200s
