options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Copy the 'utils' folder to the 'summary' folder
    # cp -r ../../utils ./ 
    # cp -r $(pwd)/utils ./ 
    cp -r $(pwd)/utils ./cloudfunctions/sentimet/utils

    cd cloudfunctions/sentimet/
    ls -la
    # Deploy the summary function
    gcloud functions deploy sentiment_function \
      --runtime python310 \
      --entry-point hello_world \
      --trigger-http \
      --region us-central1 \
      --source ./
